### ISSUE TITLE
Github Kanban project link.

### ISSUE THREAD

**Issue by NurkaAmre** [NurkaAmre/TvShowCaps#22]
Project link: https://github.com/NurkaAmre/TvShowCaps/projects/1
Team memebrs: 2

**Comment by 1GORDON** [comment]
##
## Hi @NurkaAmre 

Good job so far!

## Highlights!
- Descriptive Pull request ✔️

Hello ✋, you have done well reaching this point of the milestone 🤝 . But there are some issues that you still need to work on to go to the next project but you are almost there!

# Status: Required Changes ♻️⛔️

- [ ] Kindly make sure all cards are assigned to team members. You should see a circle with the user's avatar on each card. See the example below.
- ![kanban](https://user-images.githubusercontent.com/63917725/197547332-95b8cd42-b85e-4ea6-ae65-450b7a4e91ff.PNG)

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you consider them as they can improve your code._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread and tag me `@1GORDON` if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by NurkaAmre** [comment]
**Project link:** https://github.com/NurkaAmre/TvShowCaps/projects/1
**Team members:** 2
